# stage 1
FROM ubuntu/postgres AS base

EXPOSE 5432
WORKDIR /

# stage 2
FROM base AS path

RUN apt update
RUN apt install wget -y
RUN apt install p7zip-full -y

ENV PATH="${PATH}:/src/helia/bash"

# stage 3
FROM path AS pgmigrate

RUN apt install golang -y
RUN go install github.com/peterldowns/pgmigrate/cmd/pgmigrate@latest

# stage 4
FROM pgmigrate AS db
WORKDIR /src/helia
