services:
  engine:
    build:
      dockerfile: Dockerfile.localengine
    ports:
      - 8000:8000
      - 4000:4000
    env_file:
      - .env
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
