export class GameMessage {
  type: number;
  body: string;
}

export enum MessageTypes {
  PushInfo = -2,
  PushError = -1,
  Join = 0,
  Update = 1,
  NavClick = 2,
  CurrentShipUpdate = 3,
  Goto = 4,
  Orbit = 5,
  Dock = 6,
  Undock = 7,
  ActivateModule = 8,
  DeactivateModule = 9,
  ViewCargoBay = 10,
  CargoBayUpdate = 11,
  UnfitModule = 12,
  TrashItem = 13,
  PackageItem = 14,
  UnpackageItem = 15,
  StackItem = 16,
  SplitItem = 17,
  FitModule = 18,
  SellAsOrder = 19,
  ViewOpenSellOrders = 20,
  OpenSellOrdersUpdate = 21,
  BuySellOrder = 22,
  ViewIndustrialOrders = 23,
  IndustrialOrdersUpdate = 24,
  BuyFromSilo = 25,
  SellToSilo = 26,
  FactionUpdate = 27,
  ViewStarMap = 28,
  StarMapUpdate = 29,
  ConsumeFuel = 30,
  PlayerFactionUpdate = 31,
  SelfDestruct = 32,
  ConsumeRepairKit = 33,
  ViewProperty = 34,
  PropertyUpdate = 35,
  Board = 36,
  TransferCredits = 37,
  SellShipAsOrder = 38,
  TrashShip = 39,
  RenameShip = 40,
  PostSystemChatMessage = 41,
  TransferItem = 42,
  ViewExperience = 43,
  ExperienceUpdate = 44,
  GlobalAck = 45,
  ViewSchematicRuns = 46,
  SchematicRunsUpdate = 47,
  RunSchematic = 48,
  CreateNewFaction = 49,
  LeaveFaction = 50,
  ApplyToFaction = 51,
  ViewApplications = 52,
  ApplicationsUpdate = 53,
  ApproveApplication = 54,
  RejectApplication = 55,
  ViewMembers = 56,
  MembersUpdate = 57,
  KickMember = 58,
  UseModKit = 59,
  ViewActionReportsPage = 60,
  ActionReportsPage = 61,
  ViewActionReportDetail = 62,
  ActionReportDetail = 63,
}
